spring.application.name=pat
spring.datasource.url=jdbc:postgresql://localhost:5432/pat-java
spring.datasource.username=postgres
spring.datasource.password=1987
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
#spring.datasource.hikari.data-source-properties.loggerLevel=DEBUG
#spring.datasource.hikari.data-source-properties.logger=org.postgresql.Driver


app.jwt.secret=17f9407360f0f862167211ece609365283dc50b48fa67e718781fb0827d268e3a4ac4661641a0cda556fcae7d165e90928ea85c6fa59c4d9b63a26940eaf3c2317513eec5ae3b1209ebbea579b780ba294fbeada8435953574169a75eb8d31e3a6d5098d05b6656c374f044fcb6f86b13cb2ef314473bf1a7fe270322241e3c1e93d072e8d96f7a09db15b0def967e1dd1127391f4f4ecb623558bdc0a14252fba2766d11ccfdc479a3d32f708e4bf4a3f880cfbcbe22a40ea0022b4a700f147b94d431f235099fd4f3628a821b5e99c794a90eb082c7c6c13f6b8d6d7518964989aba2153aaf9c708071d77a588530a31c1bca0f448f1b5b1286d103de9fa51
app.jwt.expiration-ms=86400000 

dadata.token=86f3da2ca14fd23edde14e39c92bbc20fddf3adf
dadata.url=http://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
dadata.url.okved=http://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/okved2

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nastya1152ty@gmail.com
spring.mail.password=ofet xdqf rkij luuu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=5000ms
